name: Build Meridian_TWIN
on:
  workflow_dispatch:
    inputs:
      board_env:
        description: 'Select environments'
        required: true
        default: 'Meridian_TWIN_ESP32'
        type: choice
        options:
          - Meridian_TWIN_ESP32
          - Meridian_TWIN_Tsy40
      build_flags:
        description: 'Build flags'
        required: false
        type: string

jobs:
  Meridian_TWIN_ESP32:
    if: github.event.inputs.board_env == 'Meridian_TWIN_ESP32'
    uses: ./.github/workflows/_WORKFLOW_CALL_RunningPlatformIO.yml
    with:
      target_dir: Meridian_TWIN_ESP32
      board_env: esp32dev
      build_flags: ${{inputs.build_flags}}
      firmware_name: firmware_esp32dev
      firmware_ext: bin
  Meridian_TWIN_Tsy40:
    if: github.event.inputs.board_env == 'Meridian_TWIN_Tsy40'
    uses: ./.github/workflows/_WORKFLOW_CALL_RunningPlatformIO.yml
    with:
      target_dir: Meridian_TWIN_Tsy40
      board_env: teensy40
      build_flags: ${{inputs.build_flags}}
      firmware_name: firmware_teensy40
      firmware_ext: hex
